name: BlackBox Tests

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    name: Run BlackBox Tests
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Cache dependencies
        uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-blackbox

      - name: Setup PHP
        uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f # v2
        with:
          php-version: 8.3
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest

      - name: Compose Blackbox environment
        run: docker compose up -d
      - name: Run Blackbox with APC
        run: docker compose run phpunit env ADAPTER=apc vendor/bin/phpunit tests/Test/
      - name: Run Blackbox with APCng
        run: docker compose run phpunit env ADAPTER=apcng vendor/bin/phpunit tests/Test/
      - name: Run Blackbox with Redis
        run: docker compose run phpunit env ADAPTER=redis vendor/bin/phpunit tests/Test/



